insert into cozinha (id, nome) values (1, 'Tailandesa');
insert into cozinha (id, nome) values (2, 'Indiana');
insert into cozinha (id, nome) values (3, 'Francesa');
insert into restaurante (nome, taxa_frete, cozinha_id) values ('Thai Gourmet', 10.50, 1);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('Thai Delivery', 7.50, 1);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('Indiana Restaurante', 7.50, 2);
insert into formapagamento(descricao) values ("Cartão");
insert into formapagamento(descricao) values ("Debito");
insert into estado(id, uf, nome) values (1, "RS", "Rio Grande do Sul");
insert into estado(id, uf, nome) values (2, "MG", "Minas Gerais");
insert into estado(id, uf, nome) values (3, "SP", "São Paulo");
insert into estado(id, uf, nome) values (4, "RJ", "Rio de Janeiro");
insert into estado(id, uf, nome) values (5, "PR", "Parana");
insert into cidade(nome, estado_id) values ("São Paulo", 3);
insert into cidade(nome, estado_id) values ("Rio de Janeiro", 4);
insert into cidade(nome, estado_id) values ("Rio Grande do Sul", 1);